spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        check_nullability: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect